name=Dsmr3Lib
author=Willem Aandewiel (original by Matthijs Kooijman)
email=Willem@Aandewiel.nl
sentence=Lightweight tolerant reader and parser for DSMR/P1 smart meters
paragraph=
category=Data Processing
url=https://github.com/mhendriks/dsmr3Lib
architectures=*
version=0.1.0
dependencies=
core-dependencies=
