#!/bin/sh
set -eu

if [ "$#" -ne 1 ]; then
  echo "usage: $0 /path/to/p1_generator" >&2
  exit 2
fi

generator_dir=$1
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
project_dir=$(dirname -- "$script_dir")
output=$project_dir/tests/fixtures/p1_generator_telegrams.h
temporary=$output.tmp

headers="telegram.h telegramSE_FI.h A1.h Telegram_BE.h"
for header in $headers; do
  if [ ! -f "$generator_dir/$header" ]; then
    echo "missing fixture source: $generator_dir/$header" >&2
    exit 1
  fi
done

{
  echo "// Generated by tools/sync_p1_generator_fixtures.sh; do not edit."
  echo "#ifndef DSMR3_TEST_P1_GENERATOR_TELEGRAMS_H"
  echo "#define DSMR3_TEST_P1_GENERATOR_TELEGRAMS_H"
  echo
  echo "#include <stddef.h>"
  echo
  echo "namespace p1_generator_fixtures {"
  echo

  for header in $headers; do
    echo "// Source: $header"
    sed -E 's/^String ([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=/static const char \1[] =/' "$generator_dir/$header"
    echo
  done

  echo "struct TelegramFixture {"
  echo "  const char *name;"
  echo "  const char *telegram;"
  echo "};"
  echo
  echo "static const TelegramFixture all[] = {"
  for header in $headers; do
    sed -nE 's/^String ([A-Za-z_][A-Za-z0-9_]*).*/  {"\1", \1},/p' "$generator_dir/$header"
  done
  echo "};"
  echo
  echo "static const size_t count = sizeof(all) / sizeof(all[0]);"
  echo
  echo "} // namespace p1_generator_fixtures"
  echo
  echo "#endif"
} > "$temporary"

mv "$temporary" "$output"
echo "updated $output"

